OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
AUTO_SHIFT_ENABLE = yes    # Enable Autoshift on all keys
WPM_ENABLE = no            # Enable WPM logging
LTO_ENABLE = yes
CONSOLE_ENABLE = no        # Enable console functions
COMMAND_ENABLE = no        # Enable command functions
MOUSEKEY_ENABLE = no       # Enable mouse control via keyboard
EXTRAKEY_ENABLE = yes      # Enable audio and system controls
SPACE_CADET_ENABLE = no    # Enable space cadet (brackets on modifiers)
GRAVE_ESC_ENABLE = no      # Enable grave accent on Esc key
MUSIC_ENABLE = no          # Enable music functions
AUDIO_ENABLE = no          # Audio output on port C6
BLUETOOTH_ENABLE = no      # Enable Bluetooth with the Adafruit EZ-Key HID
NKRO_ENABLE = no           # USB Nkey Rollover
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality on B7 by default
MIDI_ENABLE = no           # MIDI support
UNICODE_ENABLE = no        # Unicode
BOOTMAGIC_ENABLE = no      # Virtual DIP switch configuration
ENCODER_ENABLE = no        # Enables the use of one or more encoders